### ISSUE TITLE
TypeError: cannot read property 'setSpatialReference' of undefined.

### ISSUE THREAD

**Issue by imeidopf** [ivosturm/ArcGIS#6]
Getting a console error about spatial reference. I have tried the default 102100 and the wkid 3857, but receive the following:

```
TypeError: Cannot read property 'setSpatialReference' of undefined
    at S.<computed>.E.<anonymous> (ArcGIS.js?637556528607360354:1141)
    at mxui.js?637556528607360354:5
    at S.<computed>.E._successHandler (Task.js:6)
    at S.<computed>.E._handler (QueryTask.js:11)
    at mxui.js?637556528607360354:5
    at Object.load (QueryTask.js:7)
    at eval (request.js:17)
    at b (mxui.js?637556528607360354:5)
    at v (mxui.js?637556528607360354:5)
    at e.Deferred.resolve.callback (mxui.js?637556528607360354:5) "TypeError: Cannot read property 'setSpatialReference' of undefined
    at S.<computed>.E.<anonymous> (http://localhost:8081/widgets/ArcGIS/widget/ArcGIS.js?637556528607360354:1141:21)
    at http://localhost:8081/mxclientsystem/mxui/mxui.js?637556528607360354:5:27280
    at S.<computed>.E._successHandler (http://localhost:8081/widgets/ArcGIS/lib/esri/tasks/Task.js:6:104)
    at S.<computed>.E._handler (http://localhost:8081/widgets/ArcGIS/lib/esri/tasks/QueryTask.js:11:130)
    at http://localhost:8081/mxclientsystem/mxui/mxui.js?637556528607360354:5:27280
    at Object.load (http://localhost:8081/widgets/ArcGIS/lib/esri/tasks/QueryTask.js:7:145)
    at eval (http://localhost:8081/widgets/ArcGIS/lib/esri/request.js:17:332)
    at b (http://localhost:8081/mxclientsystem/mxui/mxui.js?637556528607360354:5:47493)
    at v (http://localhost:8081/mxclientsystem/mxui/mxui.js?637556528607360354:5:47280)
    at e.Deferred.resolve.callback (http://localhost:8081/mxclientsystem/mxui/mxui.js?637556528607360354:5:48099)"
```

**Comment by ivosturm** [comment]
I assume this is because you are trying to load an ArcGIS online secured layer, which isn't supported by the widget. Could you try with a non secured layer?
